spring.application.name=spring-data-jpa-thymeleaf-crud
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.data.jdbc.dialect=postgresql
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
